# Menggunakan docker compose versi 3.7
version: '3.7'

services:
  item-app: # Service item-app
    image: ghcr.io/dede-irwanto/item-app:v1   # Image item-app dari Github Container Registry
    ports:
      - 80:8080 # Port Mapping dari port 8080 (container) ke port 80 (host)
    environment:
      MONGO_URI: mongodb://db:27017/ # Menghubungkan service item-app (aplikasi) dengan item-db (database) melalui port 27017 (port mongo-db)
    depends_on:
      - mongo-db # Memastikan mongo-db telah berjalan sebelum memulai aplikasi
    restart: always # Container akan otomatis restart ketika terhenti

  item-db: # Service item-db
    image: mongo:3 # Image mongo versi 3 dari Docker Hub
    ports:
      - "27017:27017" # Port Mapping dari port 27017 (container) ke port 27017 (host)
    volumes:
      - app-db:/data/db # Menggunakan volume app-db untuk menyimpan data

# Membuat volume app-db
volumes:
  app-db:

